-- Drops LeaveRequest.reason (requester-facing free-text).
--
-- Historical values in this column are considered disposable (confirmed 2026-04-22).
-- Rejection reasons are unaffected: they live in AuditLog metadata via
-- /api/leave/reject, never in this column.
--
-- Deploy order (prod):
--   1) Ship app code that no longer writes/reads "reason" (deployed first).
--   2) Apply this migration:
--        psql "$DATABASE_URL" -f prisma/migrations/20260422010000_drop_leave_request_reason/migration.sql
--      or:
--        pnpm prisma db execute --file prisma/migrations/20260422010000_drop_leave_request_reason/migration.sql --url "$DATABASE_URL"
--
-- Reversing this requires restoring from backup — the column and its values are gone.
ALTER TABLE "leave_requests" DROP COLUMN "reason";
